{
    'name': 'DVD Rental',
    'version': '1.0',
    'category': 'ERP Systems',
    'summary': 'DVD Rental',
    'author' : 'Mahmoud ApdelFattah Iprahim Numan',
    'depends': ['base','mail','board'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/category_data.xml',
        'data/special_feature_data.xml',
        'data/language_data.xml',
        'data/film_data.xml',
        'data/customer_data.xml',
        'data/country_data.xml',
        'data/address_data.xml',
        'data/actor_data.xml',
        'reports/payment_report.xml',
        'wizards/create_payment_wizard_view.xml',
        'views/base_menu_view.xml',
        'views/category_view.xml',
        'views/language_view.xml',
        'views/special_feature_view.xml',
        'views/film_view.xml',
        'views/country_view.xml',
        'views/customer_view.xml',
        'views/city_view.xml',
        'views/address_view.xml',
        'views/staff_view.xml',
        'views/store_view.xml',
        'views/inventory_view.xml',
        'views/actor_view.xml',
        'views/rental_view.xml',
        'views/payment_view.xml',
        'views/z_dashboard_view.xml',

    ],
    'assets':{
        'web.assets_backend':[]
    },
    'application' : True,
}